Reconfigure docker environment (#45)
* Reconfigure docker environment
* Add scss lint configuration
* Fix docker env file setup
* Get all tests to pass
* Remove duplicate env example file (wrong dir)
* Delete unnecessary dot file for jscs
* Add ignore files for bower

diff --git a/bin/init_project b/bin/init_project
--- a/bin/init_project
+++ b/bin/init_project
@@ -4,16 +4,17 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 
 . "${DIR}"/bin/lib/exitCheck.sh
 
-echo "Checking .env file..."
-if [ ! -e "$DIR"/.env ]; then
-  echo "No .env file found. Creating from .env.example..."
-  cp "$DIR"/.env.example "$DIR"/.env
-  exitCheck $?
-  echo "NOTE: Please review the .env file and configure any required parameters."
+echo "Checking Lumen .env file..."
+if [ ! -e "$DIR"/dev/.env ]; then
+    echo "No .env file found. Creating from .env.example..."
+    cp "$DIR"/dev/.env.example "$DIR"/dev/.env
+    exitCheck $?
+    echo "NOTE: Please review the .env file and configure any required parameters."
 else
-  echo ".env file exists. Skipping create."
-  echo "NOTE: Please review the .env.example file and ensure all required parameters are present in .env"
+    echo ".env file exists. Skipping create."
+    echo "NOTE: Please review the .env.example file and ensure all required parameters are present in .env"
 fi
+
 
 echo "Installing Composer dependencies..."
 "$DIR"/bin/composer install
