Make "not found" message show up again (#34)
* Show "not found" message if neither labs nor phlebotomists are nearby

* Default Behat to running WebContext

* Add setup instructions for env file

* Don't hang during init_project!

* Test that the no results message shows up

* If anyone reads this in the future: hi

diff --git a/bin/init_project b/bin/init_project
--- a/bin/init_project
+++ b/bin/init_project
@@ -4,6 +4,17 @@ DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
 
 . "${DIR}"/bin/lib/exitCheck.sh
 
+echo "Checking .env file..."
+if [ ! -e "$DIR"/web/.env ]; then
+  echo "No .env file found. Creating from .env.example..."
+  cp "$DIR"/web/.env.example "$DIR"/web/.env
+  exitCheck $?
+  echo "NOTE: Please review the .env file and configure any required parameters."
+else
+  echo ".env file exists. Skipping create."
+  echo "NOTE: Please review the .env.example file and ensure all required parameters are present in .env"
+fi
+
 echo "Installing Composer dependencies..."
 "$DIR"/bin/composer install
 exitCheck $?
@@ -17,5 +28,5 @@ echo "Installing bower dependencies..."
 exitCheck $?
 
 echo "Compiling Gulp resources..."
-"$DIR"/bin/gulp
+"$DIR"/bin/gulp stylesheet
 exitCheck $?
